import { createClient } from '@supabase/supabase-js'
import { NextResponse } from 'next/server'
import { formatPhoneID } from '@/lib/formatPhone'

function generatePassword(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789"
  let pass = ""
  for (let i = 0; i < 10; i++) {
    pass += chars[Math.floor(Math.random() * chars.length)]
  }
  return pass
}

async function sendWhatsApp(nomor: string, pesan: string) {
  const res = await fetch("https://api.fonnte.com/send", {
    method: "POST",
    headers: {
      Authorization: process.env.FONNTE_TOKEN!,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({ target: nomor, message: pesan }),
  })
  const data = await res.json()
  if (data?.status === false) {
    throw new Error(data?.reason || "Fonnte menolak permintaan")
  }
  return data
}

export async function POST(request: Request) {
  const body = await request.json()
  const { email, nama, role, wilayah, noHp } = body

  // password: kalau dikirim dari client, dipakai apa adanya (perilaku lama,
  // dipakai misalnya di halaman Kelola User buat tambah petugas/kabid manual).
  // Kalau TIDAK dikirim, server generate otomatis (dipakai di alur approve RT/RW).
  const password = body.password || generatePassword()
  const passwordWasAutoGenerated = !body.password

  // sendWhatsapp: flag eksplisit, default false. Supaya fitur lain yang
  // manggil route ini TIDAK tiba-tiba ikut kirim WA kalau tidak diminta.
  const shouldSendWhatsapp = body.sendWhatsapp === true

  const supabaseAdmin = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )

  try {
    const { data: authData, error: authError } = await supabaseAdmin.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
    })

    if (authError) throw authError

    const { error: insertError } = await supabaseAdmin.from('users').insert({
      id: authData.user.id,
      nama,
      email,
      role,
      wilayah: wilayah || null,
      no_hp: noHp || null,
      is_active: true,
    })

    if (insertError) throw insertError

    // Default response, sama persis seperti versi lama (backward-compatible)
    const response: any = { success: true, userId: authData.user.id }

    // Kirim WA HANYA kalau diminta secara eksplisit (dipakai alur approve RT/RW)
    if (shouldSendWhatsapp) {
      let whatsappSent = false
      let whatsappError: string | null = null
      let nomorFormatted = ""
      let pesanWA = ""

      if (noHp) {
        nomorFormatted = formatPhoneID(noHp)
        pesanWA =
          `Halo ${nama},\n\n` +
          `Pengajuan Anda sebagai RT/RW di SIGAP BANSOS sudah *disetujui*.\n\n` +
          `Berikut akun untuk login:\n` +
          `Email: ${email}\n` +
          `Password: ${password}\n\n` +
          `Silakan login di aplikasi dan segera ganti password Anda.\n` +
          `Terima kasih.`

        try {
          await sendWhatsApp(nomorFormatted, pesanWA)
          whatsappSent = true
        } catch (waErr: any) {
          whatsappError = waErr.message
        }
      } else {
        whatsappError = "Nomor HP tidak tersedia"
      }

      // Catat ke tabel notifikasi_log supaya muncul di halaman Monitor Notifikasi WA
      let notifLogError: string | null = null
      try {
        const { error: logInsertError } = await supabaseAdmin.from("notifikasi_log").insert({
          tujuan_no_hp: nomorFormatted || noHp || null,
          pesan: pesanWA || null,
          jenis: "approval_rtrw",
          status_kirim: whatsappSent ? "terkirim" : "gagal",
        })
        if (logInsertError) {
          notifLogError = logInsertError.message
          console.error("Gagal mencatat notifikasi_log:", logInsertError)
        }
      } catch (logErr: any) {
        notifLogError = logErr.message
        console.error("Gagal mencatat notifikasi_log:", logErr)
      }

      response.whatsappSent = whatsappSent
      response.whatsappError = whatsappError
      response.notifLogError = notifLogError
      // Password cuma dikembalikan ke client kalau WA gagal terkirim (fallback manual)
      // ATAU kalau memang tidak diminta kirim WA sama sekali tapi password auto-generate
      // (biar caller tetap bisa tampilkan/simpan sendiri kalau perlu).
      response.password = whatsappSent ? null : password
    } else if (passwordWasAutoGenerated) {
      // Kalau tidak minta kirim WA tapi password auto-generate,
      // tetap kembalikan supaya caller bisa tampilkan manual.
      response.password = password
    }

    return NextResponse.json(response)
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 400 })
  }
}